apiVersion: v1
kind: Namespace
metadata:
  name: keda
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kedacore
  namespace: keda
spec:
  interval: 24h
  url: https://kedacore.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: keda
  namespace: keda
spec:
  chart:
    spec:
      chart: keda
      version: v2.12.x
      sourceRef:
        kind: HelmRepository
        name: kedacore
        namespace: keda
  interval: 12h
  timeout: 30m
  releaseName: keda
  upgrade:
    remediation:
      retries: 20
  # https://github.com/kedacore/charts/blob/main/keda/values.yaml
  values:
    crds:
      install: true
    operator:
      name: keda-operator
      replicaCount: 1