apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: cert-manager
spec:
  interval: 24h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  interval: 12h
  timeout: 30m
  releaseName: cert-manager
  values:
    # https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/values.yaml
    installCRDs: true
    tolerations: 
    - key: "CriticalAddonsOnly"
      operator: "Exists"
      effect: "NoSchedule"
    serviceAccount:
      create: true
      annotations:
        iam.gke.io/gcp-service-account: ${cert_manager_service_account}
      automountServiceAccountToken: true
    global:
      # Limitation of GKE Autopilot. It is not possible to create resources in the kube-system namespace, and cert-manager uses the well-known kube-system to manage the leader election
      # https://cert-manager.io/docs/troubleshooting/webhook/#error-the-namespace-kube-system-is-managed-and-the-requests-verb-create-is-denied
      leaderElection:
        namespace: "cert-manager"