---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  interval: 24h
  url: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: csi-secrets-store
  namespace: kube-system
spec:
  chart:
    spec:
      chart: secrets-store-csi-driver
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: csi-secrets-store
        namespace: kube-system
  interval: 12h
  timeout: 30m
  releaseName: csi-secrets-store
  values:
    ## Install RBAC roles and bindings required for K8S Secrets syncing if true
    syncSecret:
      enabled: true
    ## Enable secret rotation feature [alpha]
    enableSecretRotation: true
    ## Secret rotation poll interval duration
    rotationPollInterval: "60s"