apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: jaegertracing
  namespace: open-telemetry
spec:
  interval: 24h
  url: https://jaegertracing.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: open-telemetry
spec:
  chart:
    spec:
      chart: jaeger
      version: v0.73.x
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: open-telemetry
  interval: 12h
  timeout: 30m
  releaseName: jaeger
  upgrade:
    remediation:
      retries: 20
  # https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/values.yaml
  values:
    provisionDataStore:
      cassandra: false
    allInOne:
      enabled: true
      args:
        - "--memory.max-traces=8000"
        - "--query.base-path=/jaeger/ui"
        - "--prometheus.server-url=http://kube-prometheus-stack-prometheus-server.monitoring:9090"
        - "--prometheus.query.normalize-calls=true"
        - "--prometheus.query.normalize-duration=true"
      extraEnv:
        - name: METRICS_STORAGE_TYPE
          value: prometheus
      resources:
        requests:
          memory: 128Mi
        limits:
          memory: 300Mi
    storage:
      type: none
    agent:
      enabled: false
    collector:
      enabled: false
    query:
      enabled: false